// In this file you can specify the trial data for your experiment


const trial_info = {

    key_pressed: [
        {
            question: "Is the shape the same or different?",
            picture: "images/1_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "1_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/1_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "1_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/1_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "1_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/1_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "1_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/2_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "2_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/2_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "2_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/2_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "2_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/2_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "2_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/3_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "3_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/3_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "3_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/3_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "3_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/3_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "3_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/4_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "4_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/4_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "4_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/4_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "4_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/4_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "4_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/5_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "5_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/5_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "5_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/5_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "5_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/5_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "5_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/6_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "6_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/6_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "6_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/6_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "6_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/6_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "6_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/7_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "7_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/7_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "7_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/7_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "7_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/7_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "7_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/8_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "8_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/8_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "8_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/8_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "8_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/8_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "8_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/9_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "9_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/9_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "9_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/9_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "9_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/9_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "9_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/10_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "10_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/10_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "10_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/10_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "10_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/10_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "10_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/11_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "11_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/11_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "11_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/11_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "11_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/11_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "11_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/12_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "12_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/12_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "12_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/12_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "12_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/12_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "12_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/13_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "13_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/13_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "13_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/13_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "13_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/13_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "13_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/14_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "14_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/14_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "14_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/14_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "14_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/14_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "14_150",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/15_50_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '50',
            number: "15_50",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/15_50_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '50',
            number: "15_50",
            congruency: "different"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/15_150_same.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'same',
            degree: '150',
            number: "15_150",
            congruency: "same"
        },
        {
            question: "Is the shape the same or different?",
            picture: "images/15_150_different.jpg",
            key1: 'f',
            key2: 'j',
            f: 'same',
            j: 'different',
            expected: 'different',
            degree: '150',
            number: "15_150",
            congruency: "different"
        }
        


    ]
};

